/**
 * Pure-function module for generating playground-data.js, playground-gen.js,
 * and playground-gen.css from a PlaygroundGraph structure. No side effects, no file I/O.
 */

import type { ViolationTrace } from "../parsers/tlc-output.js";
import type { HappyPath } from "../parsers/happy-paths.js";
import type { DisambiguatedTransition } from "../parsers/action-disambiguator.js";

export interface PlaygroundGraph {
  status: string;
  partial: boolean;
  initialStateId: string;
  states: Record<string, { label: string; vars: Record<string, unknown> }>;
  transitions: Record<string, DisambiguatedTransition[]>;
  invariants: string[];
  violations: ViolationTrace[];
  happyPaths: HappyPath[];
}

export function generatePlaygroundDataJs(opts: { title: string; graph: PlaygroundGraph }): string {
  var { title, graph } = opts;

  var lines: string[] = [];
  lines.push("// Auto-generated by tlaplus-mcp — do not edit");
  lines.push("var PLAYGROUND_TITLE = " + JSON.stringify(title) + ";");
  lines.push("var GRAPH = " + JSON.stringify({
    initialStateId: graph.initialStateId,
    states: graph.states,
    transitions: graph.transitions,
    invariants: graph.invariants,
    violations: graph.violations,
    partial: graph.partial,
  }, null, 2) + ";");

  return lines.join("\n");
}

export interface DomainLabels {
  actionLabels?: Record<string, string>;
  invariantLabels?: Record<string, string>;
  scenarioLabels?: Record<string, { title: string; description: string; rule: string | null }>;
  happyPathLabels?: Array<{ title: string; description?: string }>;
}

export function generatePlaygroundGenJs(opts: { graph: PlaygroundGraph; domainLabels?: DomainLabels }): string {
  var { graph, domainLabels } = opts;

  var actionLabels = domainLabels?.actionLabels || {};
  var scenarioLabels = domainLabels?.scenarioLabels || buildScenarioLabels(graph.violations);
  var happyPaths = buildHappyPaths(graph.happyPaths, domainLabels?.happyPathLabels);
  var invariantLabels = domainLabels?.invariantLabels || {};

  var lines: string[] = [];
  lines.push("// Auto-generated by tlaplus-mcp — do not edit");
  lines.push("var ACTION_LABELS = " + JSON.stringify(actionLabels) + ";");
  lines.push("var INVARIANT_LABELS = " + JSON.stringify(invariantLabels) + ";");
  lines.push("var SCENARIO_LABELS = " + JSON.stringify(scenarioLabels) + ";");
  lines.push("var HAPPY_PATHS = " + JSON.stringify(happyPaths, null, 2) + ";");

  return lines.join("\n");
}

export function generatePlaygroundCss(): string {
  return "/* playground-gen.css — placeholder; template styles handle everything */\n";
}

// -- Internal helpers --------------------------------------------------------

function buildScenarioLabels(violations: ViolationTrace[]): Record<string, { title: string; description: string; rule: string }> {
  var labels: Record<string, { title: string; description: string; rule: string }> = {};
  for (var v of violations) {
    var name = v.invariant || v.property || "Deadlock";
    labels[v.id] = {
      title: name,
      description: "Counterexample trace for " + name + " violation",
      rule: name,
    };
  }
  return labels;
}

function buildHappyPaths(paths: HappyPath[], labels?: Array<{ title: string; description?: string }>): Array<{ title: string; trace: HappyPath["trace"] }> {
  return paths.map(function(hp, i) {
    var label = labels?.[i];
    return {
      title: label ? label.title : "Path " + (i + 1) + " (" + hp.trace.length + " steps)",
      trace: hp.trace,
    };
  });
}

