/**
 * Pure-function module for generating playground-data.js, playground-gen.js,
 * and playground-gen.css from a PlaygroundGraph structure. No side effects, no file I/O.
 */

import type { ViolationTrace } from "../parsers/tlc-output.js";
import type { HappyPath } from "../parsers/happy-paths.js";
import type { DisambiguatedTransition } from "../parsers/action-disambiguator.js";

export interface PlaygroundGraph {
  status: string;
  partial: boolean;
  initialStateId: string;
  states: Record<string, { label: string; vars: Record<string, unknown> }>;
  transitions: Record<string, DisambiguatedTransition[]>;
  invariants: string[];
  violations: ViolationTrace[];
  happyPaths: HappyPath[];
}

export function generatePlaygroundDataJs(opts: { title: string; graph: PlaygroundGraph }): string {
  var { title, graph } = opts;

  var lines: string[] = [];
  lines.push("// Auto-generated by tlaplus-mcp — do not edit");
  lines.push("var PLAYGROUND_TITLE = " + JSON.stringify(title) + ";");
  lines.push("var GRAPH = " + JSON.stringify({
    initialStateId: graph.initialStateId,
    states: graph.states,
    transitions: graph.transitions,
    invariants: graph.invariants,
    violations: graph.violations,
    partial: graph.partial,
  }, null, 2) + ";");

  return lines.join("\n");
}

export function generatePlaygroundGenJs(opts: { graph: PlaygroundGraph }): string {
  var { graph } = opts;

  var scenarioLabels = buildScenarioLabels(graph.violations);
  var happyPaths = buildHappyPaths(graph.happyPaths);
  var invariantLabels = buildInvariantLabels(graph.invariants);
  var renderStateFn = buildRenderState(graph);

  var lines: string[] = [];
  lines.push("// Auto-generated by tlaplus-mcp — animator rewrites this file");
  lines.push("var ACTION_LABELS = {};");
  lines.push("var INVARIANT_LABELS = " + JSON.stringify(invariantLabels) + ";");
  lines.push("var SCENARIO_LABELS = " + JSON.stringify(scenarioLabels) + ";");
  lines.push("var HAPPY_PATHS = " + JSON.stringify(happyPaths, null, 2) + ";");
  lines.push("");
  lines.push(renderStateFn);
  lines.push("");
  lines.push("function renderStateVisual(vars) { return renderState(vars); }");

  return lines.join("\n");
}

export function generatePlaygroundCss(): string {
  return "/* playground-gen.css — placeholder; template styles handle everything */\n";
}

// -- Internal helpers --------------------------------------------------------

function buildScenarioLabels(violations: ViolationTrace[]): Record<string, { title: string; description: string; rule: string }> {
  var labels: Record<string, { title: string; description: string; rule: string }> = {};
  for (var v of violations) {
    var name = v.invariant || v.property || "Deadlock";
    labels[v.id] = {
      title: name,
      description: "Counterexample trace for " + name + " violation",
      rule: name,
    };
  }
  return labels;
}

function buildHappyPaths(paths: HappyPath[]): Array<{ title: string; trace: HappyPath["trace"] }> {
  return paths.map(function(hp, i) {
    return {
      title: "Path " + (i + 1) + " (" + hp.trace.length + " steps)",
      trace: hp.trace,
    };
  });
}

function buildInvariantLabels(invariants: string[]): Record<string, string> {
  var labels: Record<string, string> = {};
  for (var inv of invariants) {
    labels[inv] = inv;
  }
  return labels;
}

function buildRenderState(graph: PlaygroundGraph): string {
  // Inspect initial state vars to determine types
  var sampleVars: Record<string, unknown> = {};
  var initialState = graph.states[graph.initialStateId];
  if (initialState) {
    sampleVars = initialState.vars;
  } else {
    // Fallback: use first state
    var stateIds = Object.keys(graph.states);
    if (stateIds.length > 0) {
      sampleVars = graph.states[stateIds[0]].vars;
    }
  }

  var varNames = Object.keys(sampleVars);
  if (varNames.length === 0) {
    return [
      "function renderState(vars) {",
      '  return \'<div class="rs-empty">No variables to display</div>\';',
      "}",
    ].join("\n");
  }

  var parts: string[] = [];
  parts.push("function renderState(vars) {");
  parts.push("  var html = '';");

  for (var varName of varNames) {
    var sampleVal = sampleVars[varName];
    var renderer = pickRenderer(varName, sampleVal);
    parts.push("  // " + varName);
    parts.push('  html += \'<div class="rs-card" data-var="' + escapeJs(varName) + '">\';');
    parts.push('  html += \'<div class="rs-card-header"><span class="rs-card-title">' + escapeJs(varName) + '</span></div>\';');
    parts.push("  var v_" + safeVarName(varName) + " = vars[" + JSON.stringify(varName) + "];");
    parts.push(renderer("v_" + safeVarName(varName)));
    parts.push("  html += '</div>';");
  }

  parts.push("  return html;");
  parts.push("}");
  return parts.join("\n");
}

function pickRenderer(varName: string, sample: unknown): (accessor: string) => string {
  if (typeof sample === "string") return renderString;
  if (typeof sample === "number") return renderNumber;
  if (typeof sample === "boolean") return renderBoolean;
  if (Array.isArray(sample)) {
    if (sample.length > 0 && sample.every(function(x) { return typeof x === "string"; })) {
      return renderStringArray;
    }
    return renderArray;
  }
  if (sample !== null && typeof sample === "object") {
    var values = Object.values(sample as Record<string, unknown>);
    if (values.length > 0 && values.every(function(x) { return typeof x === "string"; })) {
      return renderRecordStringString;
    }
    if (values.length > 0 && values.every(function(x) { return typeof x === "number"; })) {
      return renderRecordStringNumber;
    }
    if (values.length > 0 && values.every(function(x) { return x !== null && typeof x === "object" && !Array.isArray(x); })) {
      return renderNestedRecord;
    }
    return renderFallback;
  }
  return renderFallback;
}

// Each renderer returns a block of JS code (as a string) that appends to `html`
// using `var` declarations for ES5 compat.

function renderString(accessor: string): string {
  return [
    "  if (typeof " + accessor + " === 'string') {",
    "    html += '<span class=\"rs-badge rs-badge-info\">' + " + accessor + " + '</span>';",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderNumber(accessor: string): string {
  return [
    "  if (typeof " + accessor + " === 'number') {",
    "    html += '<div class=\"rs-kv\"><span class=\"rs-kv-key\">" + "value" + "</span><span class=\"rs-kv-val\">' + " + accessor + " + '</span></div>';",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderBoolean(accessor: string): string {
  return [
    "  if (typeof " + accessor + " === 'boolean') {",
    "    html += '<span style=\"display:inline-block;width:10px;height:10px;border-radius:50%;background:' + (" + accessor + " ? 'var(--green)' : 'var(--text-3)') + '\"></span> ' + " + accessor + ";",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderStringArray(accessor: string): string {
  return [
    "  if (Array.isArray(" + accessor + ")) {",
    "    for (var _i = 0; _i < " + accessor + ".length; _i++) {",
    "      html += '<span class=\"rs-badge rs-badge-muted\">' + " + accessor + "[_i] + '</span> ';",
    "    }",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderArray(accessor: string): string {
  return [
    "  if (Array.isArray(" + accessor + ")) {",
    "    html += '<div class=\"rs-pipeline\">';",
    "    for (var _i = 0; _i < " + accessor + ".length; _i++) {",
    "      if (_i > 0) html += '<div class=\"rs-pipeline-arrow\"></div>';",
    "      html += '<div class=\"rs-pipeline-step\"><div class=\"rs-pipeline-dot\"></div>' + JSON.stringify(" + accessor + "[_i]) + '</div>';",
    "    }",
    "    html += '</div>';",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderRecordStringString(accessor: string): string {
  return [
    "  if (typeof " + accessor + " === 'object' && " + accessor + " !== null && !Array.isArray(" + accessor + ")) {",
    "    html += '<table class=\"rs-table\"><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody>';",
    "    var _keys = Object.keys(" + accessor + ");",
    "    for (var _i = 0; _i < _keys.length; _i++) {",
    "      html += '<tr><td>' + _keys[_i] + '</td><td><span class=\"rs-badge rs-badge-info\">' + " + accessor + "[_keys[_i]] + '</span></td></tr>';",
    "    }",
    "    html += '</tbody></table>';",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderRecordStringNumber(accessor: string): string {
  return [
    "  if (typeof " + accessor + " === 'object' && " + accessor + " !== null && !Array.isArray(" + accessor + ")) {",
    "    html += '<table class=\"rs-table\"><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody>';",
    "    var _keys = Object.keys(" + accessor + ");",
    "    for (var _i = 0; _i < _keys.length; _i++) {",
    "      html += '<tr><td>' + _keys[_i] + '</td><td>' + " + accessor + "[_keys[_i]] + '</td></tr>';",
    "    }",
    "    html += '</tbody></table>';",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderNestedRecord(accessor: string): string {
  return [
    "  if (typeof " + accessor + " === 'object' && " + accessor + " !== null && !Array.isArray(" + accessor + ")) {",
    "    var _keys = Object.keys(" + accessor + ");",
    "    for (var _i = 0; _i < _keys.length; _i++) {",
    "      html += '<div class=\"rs-card\"><div class=\"rs-card-header\"><span class=\"rs-card-title\">' + _keys[_i] + '</span></div>';",
    "      html += '<pre>' + JSON.stringify(" + accessor + "[_keys[_i]], null, 2) + '</pre>';",
    "      html += '</div>';",
    "    }",
    "  } else {",
    "    html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';",
    "  }",
  ].join("\n");
}

function renderFallback(accessor: string): string {
  return "  html += '<pre>' + JSON.stringify(" + accessor + ", null, 2) + '</pre>';";
}

function escapeJs(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/"/g, '\\"');
}

function safeVarName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, "_");
}
