/**
 * Pure-function module for generating playground-data.js, playground-gen.js,
 * and playground-gen.css from a PlaygroundGraph structure. No side effects, no file I/O.
 */

import type { ViolationTrace } from "../parsers/tlc-output.js";
import type { HappyPath } from "../parsers/happy-paths.js";
import type { DisambiguatedTransition } from "../parsers/action-disambiguator.js";

export interface PlaygroundGraph {
  status: string;
  partial: boolean;
  initialStateId: string;
  states: Record<string, { label: string; vars: Record<string, unknown> }>;
  transitions: Record<string, DisambiguatedTransition[]>;
  invariants: string[];
  violations: ViolationTrace[];
  happyPaths: HappyPath[];
}

export function generatePlaygroundDataJs(opts: { title: string; graph: PlaygroundGraph }): string {
  var { title, graph } = opts;

  var lines: string[] = [];
  lines.push("// Auto-generated by tlaplus-mcp — do not edit");
  lines.push("var PLAYGROUND_TITLE = " + JSON.stringify(title) + ";");
  lines.push("var GRAPH = " + JSON.stringify({
    initialStateId: graph.initialStateId,
    states: graph.states,
    transitions: graph.transitions,
    invariants: graph.invariants,
    violations: graph.violations,
    partial: graph.partial,
  }, null, 2) + ";");

  return lines.join("\n");
}

export function generatePlaygroundGenJs(opts: { graph: PlaygroundGraph }): string {
  var { graph } = opts;

  var scenarioLabels = buildScenarioLabels(graph.violations);
  var happyPaths = buildHappyPaths(graph.happyPaths);
  var invariantLabels = buildInvariantLabels(graph.invariants);

  var lines: string[] = [];
  lines.push("// Auto-generated by tlaplus-mcp — animator rewrites this file");
  lines.push("var ACTION_LABELS = {};");
  lines.push("var INVARIANT_LABELS = " + JSON.stringify(invariantLabels) + ";");
  lines.push("var SCENARIO_LABELS = " + JSON.stringify(scenarioLabels) + ";");
  lines.push("var HAPPY_PATHS = " + JSON.stringify(happyPaths, null, 2) + ";");
  lines.push("");
  lines.push("function renderStateVisual(vars) {");
  lines.push("  return '<div class=\"rs-empty\">Visual view not customized yet.<br>Edit <code>playground-gen.js</code> to add domain-specific rendering.</div>';");
  lines.push("}");

  return lines.join("\n");
}

export function generatePlaygroundCss(): string {
  return "/* playground-gen.css — placeholder; template styles handle everything */\n";
}

// -- Internal helpers --------------------------------------------------------

function buildScenarioLabels(violations: ViolationTrace[]): Record<string, { title: string; description: string; rule: string }> {
  var labels: Record<string, { title: string; description: string; rule: string }> = {};
  for (var v of violations) {
    var name = v.invariant || v.property || "Deadlock";
    labels[v.id] = {
      title: name,
      description: "Counterexample trace for " + name + " violation",
      rule: name,
    };
  }
  return labels;
}

function buildHappyPaths(paths: HappyPath[]): Array<{ title: string; trace: HappyPath["trace"] }> {
  return paths.map(function(hp, i) {
    return {
      title: "Path " + (i + 1) + " (" + hp.trace.length + " steps)",
      trace: hp.trace,
    };
  });
}

function buildInvariantLabels(invariants: string[]): Record<string, string> {
  var labels: Record<string, string> = {};
  for (var inv of invariants) {
    labels[inv] = inv;
  }
  return labels;
}

