/**
 * tla_state_graph — Load and analyze a TLC-generated DOT state graph.
 */

import fs from "node:fs";
import { dirname } from "node:path";
import { z } from "zod";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { parseDot } from "../parsers/dot.js";
import { parseCfg } from "../parsers/cfg.js";
import { parseTlcViolationTraces, buildGraphFromTraces } from "../parsers/tlc-output.js";
import type { ViolationTrace } from "../parsers/tlc-output.js";
import { disambiguateActions } from "../parsers/action-disambiguator.js";
import { discoverHappyPaths, type HappyPath, type HappyPathEntry } from "../parsers/happy-paths.js";
import { absolutePath } from "../lib/schemas.js";
import { formatToolResponse, formatToolError, validateFileExists } from "../lib/tool-helpers.js";

export function registerTlaStateGraph(server: McpServer): void {
  server.tool(
    "tla_state_graph",
    "Load a TLC-generated DOT state graph file and return it in a structured format for exploration. Supports raw DOT, simplified adjacency list, or full JSON format with disambiguated actions, invariants, and violation traces.",
    {
      dot_file: absolutePath
        .optional()
        .describe("Absolute path to the .dot state graph file generated by TLC (not needed in traces_only mode)"),
      cfg_file: absolutePath
        .optional()
        .describe("Absolute path to the .cfg file (for invariant/property names)"),
      tlc_output_file: absolutePath
        .optional()
        .describe("Absolute path to the TLC output file (for violation traces)"),
      tlc_output: z
        .string()
        .optional()
        .describe("Raw TLC output string (for violation traces). If both tlc_output and tlc_output_file are provided, tlc_output takes precedence."),
      format: z
        .enum(["dot", "structured", "json"])
        .default("json")
        .describe("Output format: 'dot' (raw), 'structured' (adjacency list), or 'json' (full structured output with states, transitions, violations, happy paths)"),
      traces_only: z
        .boolean()
        .default(false)
        .describe("When true, build a minimal graph from TLC output traces alone (no DOT file needed). Returns partial: true."),
      output_file: absolutePath
        .optional()
        .describe("Write JSON to this file instead of returning it inline (json format only). Response will contain a compact summary."),
    },
    async ({ dot_file, cfg_file, tlc_output_file, tlc_output, format, traces_only, output_file }) => {
      try {
        // output_file only makes sense for json format
        if (output_file && format !== "json") {
          throw new Error("output_file is only supported with json format");
        }

        // -- traces_only mode: build graph from TLC output alone ---------------
        if (traces_only) {
          if (format !== "json") {
            throw new Error("traces_only mode only supports json format");
          }

          const tlcOutputStr = tlc_output ?? (tlc_output_file ? (validateFileExists(tlc_output_file, "TLC output file"), fs.readFileSync(tlc_output_file, "utf-8")) : undefined);
          if (!tlcOutputStr) {
            throw new Error("traces_only requires tlc_output or tlc_output_file");
          }

          const traceGraph = buildGraphFromTraces(tlcOutputStr);
          const transitions = disambiguateActions(traceGraph.states, traceGraph.edges);

          const states: Record<string, { label: string; vars: Record<string, unknown> }> = {};
          for (const [id, s] of Object.entries(traceGraph.states)) {
            states[id] = { label: s.label, vars: s.vars };
          }

          let invariants: string[] = [];
          if (cfg_file) {
            validateFileExists(cfg_file, "CFG file");
            const cfgContent = fs.readFileSync(cfg_file, "utf-8");
            const cfg = parseCfg(cfgContent);
            invariants = [...cfg.invariants, ...cfg.properties];
          }

          const violationFinalStates = buildViolationFinalStates(traceGraph.violations);
          let happyPaths = discoverHappyPaths(traceGraph.initialStateId, transitions, violationFinalStates);

          // Fallback: extract non-violating prefixes from violation traces
          if (happyPaths.length === 0 && traceGraph.violations.length > 0) {
            happyPaths = extractPrefixHappyPaths(traceGraph.violations, violationFinalStates);
          }

          return buildJsonResponse({
            status: "success",
            partial: true,
            initialStateId: traceGraph.initialStateId,
            states,
            transitions,
            invariants,
            violations: traceGraph.violations,
            happyPaths,
          }, output_file);
        }

        // -- Normal mode: parse DOT file ---------------------------------------
        if (!dot_file) {
          throw new Error("dot_file is required when traces_only is false");
        }
        validateFileExists(dot_file, "DOT file");
        if (cfg_file) validateFileExists(cfg_file, "CFG file");
        if (tlc_output_file) validateFileExists(tlc_output_file, "TLC output file");

        const dotContent = fs.readFileSync(dot_file, "utf-8");
        const graph = parseDot(dotContent);

        const nodeCount = Object.keys(graph.states).length;

        // Raw DOT format
        if (format === "dot") {
          return {
            content: [
              {
                type: "text" as const,
                text: dotContent,
              },
            ],
          };
        }

        // Structured format: simplified adjacency list
        if (format === "structured") {
          const nodes = Object.entries(graph.states).map(([id, s]) => ({
            id,
            vars: s.vars,
          }));
          const edges = graph.edges.map((e) => ({
            source: e.source,
            target: e.target,
            action: e.action,
          }));

          return formatToolResponse({
            status: "success",
            node_count: nodeCount,
            edge_count: graph.edges.length,
            initial_state: graph.initialStateId,
            nodes,
            edges,
          });
        }

        // JSON format: full output
        const transitions = disambiguateActions(graph.states, graph.edges);

        // Build states map
        const states: Record<string, { label: string; vars: Record<string, unknown> }> = {};
        for (const [id, s] of Object.entries(graph.states)) {
          states[id] = { label: s.label, vars: s.vars };
        }

        // Parse CFG if provided
        let invariants: string[] = [];
        if (cfg_file) {
          const cfgContent = fs.readFileSync(cfg_file, "utf-8");
          const cfg = parseCfg(cfgContent);
          invariants = [...cfg.invariants, ...cfg.properties];
        }

        // Parse TLC output for violation traces if provided
        let violations: ViolationTrace[] = [];
        const tlcOutputStr = tlc_output ?? (tlc_output_file ? fs.readFileSync(tlc_output_file, "utf-8") : undefined);
        if (tlcOutputStr) {
          violations = parseTlcViolationTraces(tlcOutputStr, graph.states);
        }

        const violationFinalStates = buildViolationFinalStates(violations);
        const happyPaths = discoverHappyPaths(graph.initialStateId, transitions, violationFinalStates);

        return buildJsonResponse({
          status: "success",
          partial: false,
          initialStateId: graph.initialStateId,
          states,
          transitions,
          invariants,
          violations,
          happyPaths,
        }, output_file);
      } catch (err: unknown) {
        return formatToolError(err);
      }
    },
  );
}

interface StateGraphData {
  status: string;
  partial: boolean;
  initialStateId: string;
  states: Record<string, { label: string; vars: Record<string, unknown> }>;
  transitions: Record<string, import("../parsers/action-disambiguator.js").DisambiguatedTransition[]>;
  invariants: string[];
  violations: ViolationTrace[];
  happyPaths: HappyPath[];
}

function buildJsonResponse(data: StateGraphData, outputFile?: string) {
  if (!outputFile) {
    return formatToolResponse(data);
  }

  // Write full JSON to file, return compact summary
  fs.mkdirSync(dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, JSON.stringify(data), "utf-8");

  const sampleState = data.states[data.initialStateId]
    ? { vars: data.states[data.initialStateId].vars }
    : undefined;

  const transitionCount = Object.values(data.transitions).reduce(
    (sum, edges) => sum + edges.length, 0,
  );

  return formatToolResponse({
    status: data.status,
    output_file: outputFile,
    partial: data.partial,
    initialStateId: data.initialStateId,
    state_count: Object.keys(data.states).length,
    transition_count: transitionCount,
    invariants: data.invariants,
    violation_count: data.violations.length,
    happy_path_count: data.happyPaths.length,
    sample_state: sampleState,
  });
}

function buildViolationFinalStates(violations: ViolationTrace[]): Set<string> {
  const finals = new Set<string>();
  for (const v of violations) {
    if (v.type === "invariant" || v.type === "deadlock") {
      for (let i = v.trace.length - 1; i >= 0; i--) {
        if (v.trace[i].action !== "Back to state" && v.trace[i].stateId) {
          finals.add(v.trace[i].stateId!);
          break;
        }
      }
    }
  }
  return finals;
}

/**
 * Extract non-violating prefixes from violation traces as happy paths.
 * Used as a fallback in traces-only mode when BFS finds no happy paths.
 * Takes the longest prefix of each violation trace that doesn't include
 * the violating final state. Deduplicates by action sequence.
 */
function extractPrefixHappyPaths(
  violations: ViolationTrace[],
  violationFinalStates: Set<string>,
  maxPaths: number = 5,
): HappyPath[] {
  const paths: HappyPath[] = [];
  const seenActionSeqs = new Set<string>();

  for (const v of violations) {
    // Find the last non-violating index (exclude back-to-state sentinels and violation final states)
    let prefixEnd = v.trace.length;
    for (let i = v.trace.length - 1; i >= 0; i--) {
      if (v.trace[i].action === "Back to state") continue;
      if (v.trace[i].stateId && violationFinalStates.has(v.trace[i].stateId!)) {
        prefixEnd = i;
      }
      break;
    }

    // Need at least 2 states for a meaningful prefix
    if (prefixEnd < 2) continue;

    const prefix = v.trace.slice(0, prefixEnd);
    const actionSeq = JSON.stringify(prefix.map(e => e.action));
    if (seenActionSeqs.has(actionSeq)) continue;
    seenActionSeqs.add(actionSeq);

    const trace: HappyPathEntry[] = prefix.map(e => ({
      stateId: e.stateId ?? "",
      action: e.action,
    }));
    paths.push({ trace });

    if (paths.length >= maxPaths) break;
  }

  return paths;
}
