/**
 * tla_state_graph — Load and analyze a TLC-generated DOT state graph.
 */

import fs from "node:fs";
import { z } from "zod";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { parseDot } from "../parsers/dot.js";
import { parseCfg } from "../parsers/cfg.js";
import { parseTlcViolationTraces } from "../parsers/tlc-output.js";
import { disambiguateActions } from "../parsers/action-disambiguator.js";

const MAX_NODES = 50_000;

export function registerTlaStateGraph(server: McpServer): void {
  server.tool(
    "tla_state_graph",
    "Load a TLC-generated DOT state graph file and return it in a structured format for exploration. Supports raw DOT, simplified adjacency list, or full playground format with disambiguated actions, invariants, and violation traces.",
    {
      dot_file: z.string().describe("Absolute path to the .dot state graph file generated by TLC"),
      cfg_file: z
        .string()
        .optional()
        .describe("Absolute path to the .cfg file (for invariant/property names)"),
      tlc_output_file: z
        .string()
        .optional()
        .describe("Absolute path to the TLC output file (for violation traces)"),
      format: z
        .enum(["dot", "structured", "playground"])
        .default("playground")
        .describe("Output format: 'dot' (raw), 'structured' (adjacency list), or 'playground' (full)"),
    },
    async ({ dot_file, cfg_file, tlc_output_file, format }) => {
      try {
        const dotContent = fs.readFileSync(dot_file, "utf-8");
        const graph = parseDot(dotContent);

        const nodeCount = Object.keys(graph.states).length;

        // Enforce size limit
        if (nodeCount > MAX_NODES) {
          return {
            content: [
              {
                type: "text" as const,
                text: JSON.stringify({
                  error: "State graph too large",
                  node_count: nodeCount,
                  too_large: true,
                }),
              },
            ],
            isError: true,
          };
        }

        // Raw DOT format
        if (format === "dot") {
          return {
            content: [
              {
                type: "text" as const,
                text: dotContent,
              },
            ],
          };
        }

        // Structured format: simplified adjacency list
        if (format === "structured") {
          const nodes = Object.entries(graph.states).map(([id, s]) => ({
            id,
            vars: s.vars,
          }));
          const edges = graph.edges.map((e) => ({
            source: e.source,
            target: e.target,
            action: e.action,
          }));

          return {
            content: [
              {
                type: "text" as const,
                text: JSON.stringify(
                  {
                    node_count: nodeCount,
                    edge_count: graph.edges.length,
                    initial_state: graph.initialStateId,
                    nodes,
                    edges,
                  },
                  null,
                  2,
                ),
              },
            ],
          };
        }

        // Playground format: full output
        const transitions = disambiguateActions(graph.states, graph.edges);

        // Build states map for playground
        const states: Record<string, { label: string; vars: Record<string, unknown> }> = {};
        for (const [id, s] of Object.entries(graph.states)) {
          states[id] = { label: s.label, vars: s.vars };
        }

        // Parse CFG if provided
        let invariants: string[] = [];
        if (cfg_file) {
          const cfgContent = fs.readFileSync(cfg_file, "utf-8");
          const cfg = parseCfg(cfgContent);
          invariants = [...cfg.invariants, ...cfg.properties];
        }

        // Parse TLC output for violation traces if provided
        let violations: unknown[] = [];
        if (tlc_output_file) {
          const tlcOutput = fs.readFileSync(tlc_output_file, "utf-8");
          violations = parseTlcViolationTraces(tlcOutput, graph.states);
        }

        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(
                {
                  initialStateId: graph.initialStateId,
                  states,
                  transitions,
                  invariants,
                  violations,
                },
                null,
                2,
              ),
            },
          ],
        };
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: msg }) }],
          isError: true,
        };
      }
    },
  );
}
